filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app_logs/app.log
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["host.docker.internal:9200"]

setup.ilm.policy_name: "invoice-app-logs-policy"
setup.ilm.overwrite: true